plugin:
  default_locale: 'en_US'
  available_locales: [en_US]

settings:
  motd: true
  rules: true
  chat: true


motd:
  - "Running &b<plugin>&f by &b<authors>&f"
  - "Welcome to the server, &b<name>&f!"
  - "Enjoy your stay, and don't get lost!"

rules:
  - "1: Be courteous."
  - "2: Don't beg ops for items."
  - "3: Have fun!"