name: CommandSuite
main: net.krinsoft.commandsuite.CommandSuite
version: ${project.version}
authors: [krinsdeath]
depend: []

commands:
  # item based commands
  # -------------------
  give:
    aliases: [g]
    description: Gives items to a player
    permission: commandsuite.items.give
    usage: /<command> (player) (item[:data]) [amount]
  item:
    aliases: [i]
    description: Gives the sender the specified item(s)
    permission: commandsuite.items.item
    usage: /<command> (item[:data]) [amount]
  max:
    aliases: [m, more]
    description: Sets the item currently in the sender's hand to the max stack size
    permission: commandsuite.items.max
    usage: /<command>
  # administrative commands
  # -------------------
  time:
    aliases: [day]
    description: Sets the time
    permission: commandsuite.admins.time
    usage: |
      /<command> set [val]    - sets the time to the specified value, or 0
      /<command> add [val]    - adds the specified value to the current time, or 0
      /<command> day          - sets it to day
      /<command> dusk         - sets it to dusk
      /<command> night        - sets it to night
      /<command> dawn         - sets it to dawn
  weather:
    aliases: [storm, rain, snow]
    description: Changes the weather
    permission: commandsuite.admins.weather
    usage: |
      /weather [type] - Type can be any of rain, snow, storm
      /snow - Shortcut for /weather snow
      /rain - Shortcut for /weather rain
      /storm - Shortcut for /weather storm
  kick:
    description: Kicks a player from the server
    permission: commandsuite.admins.kick
    usage: /<command> (player) [reason]
  ban:
    description: Bans a player (and his IP) from the server
    permission: commandsuite.admins.ban
    usage: |
      /<command> (player) [reason]
  pardon:
    aliases: [unban]
    description: Unbans a player (and his IP) from the server
    permission: commandsuite.admins.unban
    usage: /<command> (player)
  say:
    aliases: [broadcast, bc]
    description: Broadcasts a message to all players on all worlds
    permission: commandsuite.admins.say
    usage: /<command> (message)
  # miscellaneous commands
  # -------------------
  list:
    description: Lists online players (and their worlds)
    permission: commandsuite.basic.list
    usage: /<command>
  who:
    description: Lists the specified player's world and afk status
    permission: commandsuite.basic.who
    usage: /<command> (player)
  where:
    description: Gets information about the player specified
    permission: commandsuite.basic.where
    usage: /<command> (player)

permissions:
  # basic command permissions
  commandsuite.basic.motd:
    description: Grants access to '/motd'
    default: false
  commandsuite.basic.rules:
    description: Grants access to '/rules'
    default: false
  commandsuite.basic.afk:
    description: Grants access to '/afk'
    default: false
  commandsuite.basic.list:
    description: Grants access to '/list'
    default: false
  commandsuite.basic.who:
    description: Grants access to the basic version of '/who'
    default: false
  commandsuite.basic.where:
    description: Grants access to '/where'
    default: false
  commandsuite.basic.*:
    description: Grants access to all 'basic' nodes
    default: true
    children:
      commandsuite.basic.motd: true
      commandsuite.basic.rules: true
      commandsuite.basic.afk: true
      commandsuite.basic.list: true
      commandsuite.basic.who: true
      commandsuite.basic.where: true
  # item command permissions
  commandsuite.items.give:
    description: Grants access to '/give'
    default: false
  commandsuite.items.item:
    description: Grants access to '/item'
    default: false
  commandsuite.items.max:
    description: Grants access to '/max'
    default: false
  commandsuite.items.*:
    description: Grants access to all 'items' nodes
    default: op
    children:
      commandsuite.items.give: true
      commandsuite.items.item: true
      commandsuite.items.max: true
  # admin command permissions
  commandsuite.admins.time:
    description: Grants access to '/time'
    default: false
  commandsuite.admins.weather:
    description: Grantas access to '/weather'
    default: false
  commandsuite.admins.kick:
    description: Grants access to '/kick'
    default: false
  commandsuite.admins.ban:
    description: Grants access to '/ban'
    default: false
  commandsuite.admins.unban:
    description: Grants access to '/unban'
    default: false
  commandsuite.admins.who:
    description: Grants access to the admin version of '/who'
    default: false
  commandsuite.admins.say:
    description: Grants access to '/say'
    default: false
  commandsuite.admins.*:
    description: Grants access to all 'admin' nodes
    default: op
    children:
      commandsuite.admins.time: true
      commandsuite.admins.weather: true
      commandsuite.admins.kick: true
      commandsuite.admins.ban: true
      commandsuite.admins.unban: true
      commandsuite.admins.who: true
      commandsuite.admins.say: true
  # node templates
  commandsuite.*:
    description: Grants access to all commands
    default: false
    children:
      commandsuite.basic.*: true
      commandsuite.items.*: true
      commandsuite.admins.*: true